# all available options: https://goreleaser.com/customization/
project_name: dev-flow

before:
  hooks: []

builds:
- binary: dev-flow
  env:
  - CGO_ENABLED=0
  goos:
  - darwin  # MacOS
  - windows
  - linux
  goarch:
  - amd64
  ldflags: []

archive:
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
  format_overrides:
  - goos: windows
    format: zip
  files:
    - none*  # only package the binary - not defaults: readme, license, changelog

checksum:
  name_template: 'SHA256SUMS.txt'

brew:
  description: CLI for standardizing and automating common development tasks
  homepage: https://github.com/cyberark/dev-flow
  url_template: https://github.com/cyberark/dev-flow/releases/download/v{{.Version}}/summon-conjur-darwin-amd64.tar.gz
  install: |
    bin.install "dev-flow"
  test: |
    system "#{bin}/dev-flow", "-h"
  
  github:
    owner: cyberark
    name: homebrew-tools
  skip_upload: true

nfpm:
  name_template: "{{.ProjectName}}"
  vendor: CyberArk
  homepage: https://github.com/cyberark/dev-flow
  maintainer: John Tuttle <john.tuttle@cyberark.com>

  description: CLI for standardizing and automating common development tasks
  license: Apache2.0
  formats:
  - deb
  - rpm
  bindir: /usr/local/bin

release:
  disable: true
